// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//
//  Creation Date: Jan 2000
//
//	Description:
//  Converts version 2.80 preferences to version 2.81
//
{
	// Remove defunct optionVars that are not longer
	// used because of the preference window rewrite.
	//
	catch (
		`optionVar
			-remove generalPrefSaveOnQuit
			-remove selectPrefSaveOnQuit
			-remove displayPrefSaveOnQuit
			-remove manipPrefSaveOnQuit
			-remove modelPrefSaveOnQuit
			-remove animPrefSaveOnQuit
			-remove kinPrefSaveOnQuit
			-remove dynPrefSaveOnQuit
			-remove unitPrefSaveOnQuit
			-remove saveUIPrefOnExit
			-remove saveWindowPrefOnExit
			-remove saveLinesPrefOnExit
			-remove saveMiscUIPrefOnExit
			-remove saveShelfState
			-remove savePanelState`
	);

	// There were 2 of these defined for the same thing.
	// Keeping clickBoxSize and removing this one.
	//
	catch (`optionVar -remove clickBoxSelect`);

	// The main window and command window now have their
	// positions saved like any other window.  But we need
	// to set this from the old optionVars the first time.
	//
	// Note: We can't use $gMainWindow or $gCommandWindow
	// as they have not been set yet.
	//

	if (`optionVar -exists mainWindowTopPos`) {

		windowPref 
			-tlc `optionVar -q "mainWindowTopPos"` `optionVar -q "mainWindowLeftPos"`
			-wh  `optionVar -q "mainWindowWidth"`  `optionVar -q "mainWindowHeight"`
			MayaWindow;

		windowPref 
			-tlc `optionVar -q "cmdWindowTopPos"`  `optionVar -q "cmdWindowLeftPos"`
			-wh  `optionVar -q "cmdWindowWidth"`   `optionVar -q "cmdWindowHeight"`
			CommandWindow;

		optionVar
			-remove mainWindowTopPos
			-remove mainWindowLeftPos
			-remove mainWindowWidth
			-remove mainWindowHeight
			-remove cmdWindowTopPos
			-remove cmdWindowLeftPos
			-remove cmdWindowWidth
			-remove cmdWindowHeight;
	}
}

