// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
global proc MASHnNetwork()
{

    string $sel[] = `ls -sl -tr`;
    string $waiter = `createNode MASH_Waiter`;

    string $instancer;
    $instancer = `createNode instancer`;

    for ($trans in $sel) {
        instancer -e -a -obj $trans $instancer;
    }

    connectAttr -force ($waiter +".outputPoints") ($instancer +".inputPoints");

    string $nParticle[] = `nParticle`;
    string $emitter[] = `emitter -pos 0 0 0 -type omni -r 100 -sro 0 -nuv 0 -cye none -cyi 1 -spd 1 -srn 0 -nsp 1 -tsp 0 -mxd 0 -mnd 0 -dx 1 -dy 0 -dz 0 -sp 0` ;

    connectDynamic -em $emitter[0] $nParticle[0];

    connectAttr -force ($nParticle[1]+".position") ($waiter+".inputArray");

    connectAttr -f ($nParticle[1]+".count") ($waiter+".numberOfOutputs");

    setAttr ($waiter+".particleMode") 1;

}
