// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================

global proc createPolyPlatonicSolidProperties()
{
	// Global template variables for form spacing
	global int $gToolOptionBoxTemplateDescriptionMarginWidth;
	global int $gToolOptionBoxTemplateFrameSpacing;
	
	global float $gDodecahedronRatio;
	
	string $parent = `toolPropertyWindow -q -location`;
	setParent $parent;
	
	setUITemplate -pushTemplate ToolOptionBoxTemplate;

	string $type = "createPolyPlatonicSolid";
	string $title = (uiRes("m_createPolyPlatonicSolidProperties.kCreatePolyPlatonicSolidToolSettings"));

	string $axis = `upAxis -q -axis`;
	
	int $axisButton = 1;
	
	if ($axis == "z")
		$axisButton = 2;
	else
		$axisButton = 1;

	// Form layout
	$parent = `formLayout $type`;

		// Description frame
		string $descriptionFrame = 
		`frameLayout -label (uiRes("m_createPolyPlatonicSolidProperties.kDescriptionFrame")) -mw $gToolOptionBoxTemplateDescriptionMarginWidth`;

			text -label (uiRes("m_createPolyPlatonicSolidProperties.kCreatePolyPlatonicSolidToolDescApp")) createPolyPlatonicSolidToolDescLabel;			
	
		setParent $parent;

		// Create Settings frame
		string $settingsFrame = 
		`frameLayout -label (uiRes("m_createPolyPlatonicSolidProperties.kCreateSettingsFrame"))`;
			columnLayout;

				optionMenuGrp -label (uiRes("m_createPolyPlatonicSolidProperties.kPlatonicType")) createPolyPlatonicSolidTypeOptionMenuGrp;
					menuItem -label (uiRes("m_createPolyPlatonicSolidProperties.kDodecahedron"));
					menuItem -label (uiRes("m_createPolyPlatonicSolidProperties.kIcosahedron"));
					menuItem -label (uiRes("m_createPolyPlatonicSolidProperties.kOctahedron"));
					menuItem -label (uiRes("m_createPolyPlatonicSolidProperties.kTetrahedron"));
					
				checkBoxGrp -label1 (uiRes("m_createPolyPlatonicSolidProperties.kCreateUVs"))
					-label (uiRes("m_createPolyPlatonicSolidProperties.kTextureMapping"))
					-value1 true
					-enable true
					createPolyPlatonicSolidCreateUVCheckBox;
				
				checkBoxGrp -label1 (uiRes("m_createPolyPlatonicSolidProperties.kNormalize")) 
					-value1 true
					-enable true
					createPolyPlatonicSolidNormalizeCheckBox;
				
				radioButtonGrp 
					-numberOfRadioButtons 2
					-label1 (uiRes("m_createPolyPlatonicSolidProperties.kCollectively")) 
					-label2 (uiRes("m_createPolyPlatonicSolidProperties.kEachFaceSep"))
					-select 1
					-enable true
					-vertical
					createPolyPlatonicSolidNormalizeTypeRadioButton;
				
				checkBoxGrp -label1 (uiRes("m_createPolyPlatonicSolidProperties.kPreserveAR"))
					-value1 true
					-enable true
					createPolyPlatonicSolidPreserveAspectRatioCheckBox;

		setParent $parent;	

		// Single-click Settings frame
		string $singleClickSettingsFrame = 
		`frameLayout -label (uiRes("m_createPolyPlatonicSolidProperties.kSettingsFrame"))`;
			columnLayout;

				floatSliderGrp -field true -l (uiRes("m_createPolyPlatonicSolidProperties.kRadius"))
					-min 0.01 -max 10.0 -v 1.0 -fieldMaxValue 10000 createPolyPlatonicSolidRadiusSlider;

				floatSliderGrp -field true -l (uiRes("m_createPolyPlatonicSolidProperties.kSideLength"))
					-min 0.01 -max 10.0 -v $gDodecahedronRatio -fieldMaxValue 1000 createPolyPlatonicSolidSideLengthSlider;
					
				radioButtonGrp -label (uiRes("m_createPolyPlatonicSolidProperties.kAxis"))
					-numberOfRadioButtons 3
					-label1 (uiRes("m_createPolyPlatonicSolidProperties.kXAxis"))
					-label2 (uiRes("m_createPolyPlatonicSolidProperties.kYAxis"))
					-label3 (uiRes("m_createPolyPlatonicSolidProperties.kZAxis"))
					-enable true
					-select $axisButton
					createPolyPlatonicSolidAxisRadioButton;

	setParent ..;

	// Attach Description/Settings frames to form layout
	formLayout -e
		-af $descriptionFrame "top" $gToolOptionBoxTemplateFrameSpacing
		-af $descriptionFrame "left" $gToolOptionBoxTemplateFrameSpacing
		-af $descriptionFrame "right" $gToolOptionBoxTemplateFrameSpacing
		-an $descriptionFrame "bottom"

		-ac $singleClickSettingsFrame "top" $gToolOptionBoxTemplateFrameSpacing $descriptionFrame
		-af $singleClickSettingsFrame "left" $gToolOptionBoxTemplateFrameSpacing
		-af $singleClickSettingsFrame "right" $gToolOptionBoxTemplateFrameSpacing
		-an $singleClickSettingsFrame "bottom" 

		-ac $settingsFrame "top" $gToolOptionBoxTemplateFrameSpacing $singleClickSettingsFrame
		-af $settingsFrame "left" $gToolOptionBoxTemplateFrameSpacing
		-af $settingsFrame "right" $gToolOptionBoxTemplateFrameSpacing
		-an $settingsFrame "bottom" 

	$parent;

	setUITemplate -popTemplate;
}
