// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//  Description:
//      Create the menu for the gameFbxExporter plug-in

global proc gameFbxExporterCreateMenu()
{
    global string $gMainWindow;  // defined by Maya
     
    setParent $gMainWindow;
    
    // Create the Game FBX exporter menu as a main file menu item.
    if (`menu -q -exists mainFileMenu`) 
    {
        setParent -menu mainFileMenu;    
        if (!`menuItem -q -exists gameFbxExporterMenu`)            
        {
            // Insert Game FBX Exporter menu
            menuItem -divider true -insertAfter exportActiveFileOptions gameFbxExporterDivider;
            // Note: the game pipeline plug-in menu are inserting their menu items in the same location, the menu can have a different position when it is loaded.
            menuItem -version "2016" -label (getPluginResource( "gameFbxExporter", "kGameExporterWindowTitle" )) -insertAfter gameFbxExporterDivider -command "gameFbxExporter" gameFbxExporterMenu;           
        }         
    }
}


global proc gameFbxExporterDeleteMenu()
{    
    // Delete Game Fbx Exporter menu 
    // Called by the uninitialize plug-in function
    if (`menuItem -q -exists gameFbxExporterMenu`) 
    {       
        deleteUI -menuItem gameFbxExporterDivider;
        deleteUI -menuItem gameFbxExporterMenu;
    }    
}
