// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
global proc mtk_saveToolOptions()
{
	////////////////////////////////////////////////////////////////////////////////
	// Live surface options
	int $intVal = `nexOpt -q useMeshAlpha`;
	optionVar -iv quadDrawUseMeshAlpha $intVal;

	float $fltVal = `nexOpt -q meshAlpha`;
	optionVar -fv quadDrawMeshAlpha $fltVal;

	$intVal = `nexOpt -q useMeshOffset`;
	optionVar -iv quadDrawUseMeshOffset $intVal;

	$fltVal = `nexOpt -q meshOffset`;
	optionVar -fv quadDrawMeshOffset $fltVal;

	$intVal = `nexOpt -q overlayAppendMesh`;
	optionVar -iv quadDrawOverlayAppendMesh $intVal;

	float $fltArr[] = `nexOpt -q appendMeshColor`;
	optionVar -fv4 quadDrawOverlayAppendMeshColor $fltArr[0] $fltArr[1] $fltArr[2] $fltArr[3];

	$intVal = `nexOpt -q useMeshColorOverride`;
	optionVar -iv quadDrawUseMeshColorOverride $intVal;

	$fltArr = `nexOpt -q meshColorOverride`;
	optionVar -fv3 quadDrawMeshColorOverride $fltArr[0] $fltArr[1] $fltArr[2];

	$intVal = `nexOpt -q snapToBackfaces`;
	optionVar -iv quadDrawSnapToBackfaces $intVal;

	////////////////////////////////////////////////////////////////////////////////
	// Quad Draw options
	$intVal = `nexOpt -q useAutoWeld`;
	optionVar -iv quadDrawAutoWeld $intVal;

	$intVal = `nexOpt -q autoWeldTolerance`;
	optionVar -iv quadDrawAutoWeldTolerance $intVal;

	$intVal = `nexOpt -q relaxAffects`;
	optionVar -iv quadDrawRelax $intVal;

	$intVal = `nexOpt -q extendType`;
	optionVar -iv quadDrawExtend $intVal;

	$intVal = `nexOpt -q quaDrawStripSize`;
	optionVar -iv quadDrawStripSize $intVal;

	////////////////////////////////////////////////////////////////////////////////
	// Multi-Cut options
	$intVal = `nexOpt -q cutSnapAngle`;
	optionVar -iv multiCutSnapStep $intVal;

	$intVal = `nexOpt -q cutSmoothingAngle`;
	optionVar -iv multiCutSmoothingAngle $intVal;

	$intVal = `nexOpt -q useEdgeFlow`;
	optionVar -iv multiCutUseEdgeFlow $intVal;

	$fltVal = `nexOpt -q edgeFlowValue`;
	optionVar -fv multiCutEdgeFlow $fltVal;

	$intVal = `nexOpt -q cutSubdivisions`;
	optionVar -iv multiCutSubdivisions $intVal;

	$intVal = `nexOpt -q useDeleteFaces`;
	optionVar -iv multiCutDeleteFaces $intVal;

	$intVal = `nexOpt -q useExtractFaces`;
	optionVar -iv multiCutExtractFaces $intVal;

	$intVal = `nexOpt -q sliceIgnoreBackfaces`;
	optionVar -iv multiCutIgnoreBackfaces $intVal;

	$fltArr[0] = `nexOpt -q extractFacesX`;
	$fltArr[1] = `nexOpt -q extractFacesY`;
	$fltArr[2] = `nexOpt -q extractFacesZ`;
	optionVar -fv3 multiCutExtractOffset $fltArr[0] $fltArr[1] $fltArr[2];

	$fltArr = `nexOpt -q hiliteColorCutLine`;
	optionVar -fv3 multiCutHiliteColorLine $fltArr[0] $fltArr[1] $fltArr[2];

	$fltArr = `nexOpt -q hiliteColorCutVert`;
	optionVar -fv3 multiCutHiliteColorVert $fltArr[0] $fltArr[1] $fltArr[2];

	$fltArr = `nexOpt -q hiliteColorCutEdge`;
	optionVar -fv3 multiCutHiliteColorEdge $fltArr[0] $fltArr[1] $fltArr[2];

	$fltArr = `nexOpt -q hiliteColorCutFace`;
	optionVar -fv3 multiCutHiliteColorFace $fltArr[0] $fltArr[1] $fltArr[2];

	////////////////////////////////////////////////////////////////////////////////
	// Connect options
	string $strVal = `nexOpt -q connectCurLmbMap`;
	optionVar -sv connectToolMode $strVal;

	// Connect preferences need to be moved to nexOpt since nexCtx can only be used if
	// the connect tool is active which means they will never be saved/loaded correctly.
	int $connectToolActive = (`nexOpt -q manipType` == "connect");

	if ($connectToolActive) {
		$fltVal = `nexCtx -getManipVal connect slide`;
		optionVar -fv connectToolSlide $fltVal;

		$intVal = `nexCtx -getManipVal connect segments`;
		optionVar -iv connectToolSegments $intVal;

		$fltVal = `nexCtx -getManipVal connect pinch`;
		optionVar -fv connectToolPinch $fltVal;
	}
}
