// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
// Create popup menu for the extrude face node options.
// This is called from the showManipsCtx which already
// has the parent menu set.
//

global proc polyExtrudeFaceOptionsPopup( string $node )
{
	int $kftValue = `getAttr ($node + ".keepFacesTogether")`;
	string $kftLabel = (uiRes("m_polyExtrudeFaceOptionsPopup.kKeepFacesTogetherLabel"));
	string $kftCommand = ("setAttr " + $node + ".keepFacesTogether " + !($kftValue));

	string $shEdgeLabel = (uiRes("m_polyExtrudeFaceOptionsPopup.kSoftenHardenLabel"));

	string $sEdgeLabel = (uiRes("m_polyExtrudeFaceOptionsPopup.kSoftenLabel"));
	string $sEdgeCommand = ("setAttr " + $node + ".smoothingAngle 180");

	string $hEdgeLabel = (uiRes("m_polyExtrudeFaceOptionsPopup.kHardenLabel"));
	string $hEdgeCommand = ("setAttr " + $node + ".smoothingAngle 0");

    string $ofstLabel = (uiRes("m_polyExtrudeFaceOptionsPopup.kOffsetLabel"));	
	string $ofstCommand = ("showManipCtx -e -setAttrActive offset showManip3D;");

	string $dvsLabel =  (uiRes("m_polyExtrudeFaceOptionsPopup.kDivisionsLabel"));
	string $dvsCommand = ("showManipCtx -e -setAttrActive divisions showManip3D;");

	string $thksLabel =  (uiRes("m_polyExtrudeFaceOptionsPopup.kThicknessLabel"));
	string $thksCommand = ("showManipCtx -e -setAttrActive thickness showManip3D;");

	string $lTrnsltZLabel =  (uiRes("m_polyExtrudeFaceOptionsPopup.kLaterTranslationZLabel"));
	string $lTrnsltZCommand = ("showManipCtx -e -setAttrActive localTranslateZ showManip3D;");

	int $showSlidersOptVar[] = `manipOptions -q -showExtrudeSliders`;
	string $showSlidersCommand = (" manipOptions -showExtrudeSliders " + (!$showSlidersOptVar[0]) + ";");

	menuItem 
		-label $ofstLabel	
		-radialPosition	"W"
		-command $ofstCommand
		;

	menuItem 
		-label $dvsLabel	
		-radialPosition	"N"
		-command $dvsCommand
		;

	menuItem 
		-label $thksLabel	
		-radialPosition	"E"
		-command $thksCommand
		;

	menuItem 
		-label $lTrnsltZLabel	
		-radialPosition	"SW"
		-command $lTrnsltZCommand
		;

	menuItem 
		-label $kftLabel	
		-radialPosition	"S"
		-command $kftCommand
		;
		
	menuItem 
		-label $shEdgeLabel
		-radialPosition	"SE"
		-subMenu 1
		;

		menuItem
			-label $sEdgeLabel
			-command $sEdgeCommand
			-radialPosition "SE" 
			-enableCommandRepeat 1
			;

		menuItem
			-label $hEdgeLabel
			-command $hEdgeCommand
			-radialPosition "NE" 
			-enableCommandRepeat 1
			;

	setParent -m ..;
}
