// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
// Resources for Plug-in: dx11Shader
// 
// ----------------------------
// Registered string resources:
// ----------------------------
setPluginResource( "dx11Shader", "kActionChoose", "ボタン アクションを選択:");
setPluginResource( "dx11Shader", "kActionEdit", "アクション定義を編集");
setPluginResource( "dx11Shader", "kActionEditorClose", "閉じる");
setPluginResource( "dx11Shader", "kActionEditorCommands", "コマンド");
setPluginResource( "dx11Shader", "kActionEditorCreate", "作成");
setPluginResource( "dx11Shader", "kActionEditorDelete", "削除");
setPluginResource( "dx11Shader", "kActionEditorDescription", "説明");
setPluginResource( "dx11Shader", "kActionEditorImageFile", "イメージ ファイル");
setPluginResource( "dx11Shader", "kActionEditorInsertVariable", "変数を挿入:");
setPluginResource( "dx11Shader", "kActionEditorName", "名前");
setPluginResource( "dx11Shader", "kActionEditorSave", "保存");
setPluginResource( "dx11Shader", "kActionEditorTitle", "dx11Shader ツール ボタン エディタ");
setPluginResource( "dx11Shader", "kActionEmptyCommand", "LMB: 何も実行しない、空のコマンドです。RMB: このボタンで実行する操作を選択します。");
setPluginResource( "dx11Shader", "kActionNew", "新しいアクション...");
setPluginResource( "dx11Shader", "kActionNewAnnotation", "新しいアクションをこのメニューに追加します");
setPluginResource( "dx11Shader", "kActionNotAssigned", "LMB: 何も実行しないため、割り当てられません。RMB: このボタンで実行する操作を選択します。");
setPluginResource( "dx11Shader", "kActionNothing", "(なし)");
setPluginResource( "dx11Shader", "kActionNothingAnnotation", "ボタンは何も実行しないため、割り当てられません。");
setPluginResource( "dx11Shader", "kAmbient", "アンビエント");
setPluginResource( "dx11Shader", "kDiagnostics", "診断");
setPluginResource( "dx11Shader", "kEditAnnotationLNX", "エディタで fx ファイルを編集します");
setPluginResource( "dx11Shader", "kEditAnnotationMAC", "テキスト編集で fx ファイルを編集します");
setPluginResource( "dx11Shader", "kEditAnnotationWIN", "fx ファイルに関連付けられたアプリケーションで編集します");
setPluginResource( "dx11Shader", "kEditCommandLNX", "この機能を使用する前にコマンドを設定してください。");
setPluginResource( "dx11Shader", "kEditTool", "編集");
setPluginResource( "dx11Shader", "kEffectFiles", "エフェクト ファイル");
setPluginResource( "dx11Shader", "kErrorAbsolutePathNotFound", "エフェクト ファイル \"^1s\" は見つからないため、代わりに \"^2s\" を使用します。\n");
setPluginResource( "dx11Shader", "kErrorConeAngle", "ConeAngle データの取得エラー");
setPluginResource( "dx11Shader", "kErrorDeregisterNodeType", "filePathEditor から ^1s を登録解除できませんでした");
setPluginResource( "dx11Shader", "kErrorEffectBuffer", "バッファ作成エフェクトのエラー: {\n^1s\n}\n");
setPluginResource( "dx11Shader", "kErrorEffectCompile", "ファイル コンパイル エラーからの効果(^1s) {\n^2s\n}\n");
setPluginResource( "dx11Shader", "kErrorFileNotFound", "エフェクト ファイル \"^1s\" が見つかりません。");
setPluginResource( "dx11Shader", "kErrorIndexVaryingParameter", "変更パラメータ ^1s でサポートされていないインデックスです。インデックスは 0 として解釈されます\n");
setPluginResource( "dx11Shader", "kErrorIsTransparentOpacity", "isTransparent == 2 注釈を使用する技法には、不透明セマンティックを持つ 1 つのパラメータが必要です。\n");
setPluginResource( "dx11Shader", "kErrorLog", "エラー:\n^1s");
setPluginResource( "dx11Shader", "kErrorNoValidTechniques", "技法を初期化できません。効果に有効な技法がありません。\n");
setPluginResource( "dx11Shader", "kErrorPenumbraAngle", "PenumbraAngle データの取得エラー");
setPluginResource( "dx11Shader", "kErrorRegisterNodeType", "filePathEditor に ^1s を登録できませんでした");
setPluginResource( "dx11Shader", "kErrorSetPass", "パスの設定に失敗しました。パス #^1s は技法 ^2s に存在しません。\n");
setPluginResource( "dx11Shader", "kErrorSetTechniqueByIndex", "技法の設定に失敗しました。技法 #^1s は効果に存在しません。\n");
setPluginResource( "dx11Shader", "kErrorSetTechniqueByName", "技法の設定に失敗しました。技法 ^1s は効果に存在しません。\n");
setPluginResource( "dx11Shader", "kErrorUnknownIsTransparent", "技法に不明な isTransparent 注釈値(0: 不透明、1: 透明、2: 不透明セマンティクを使用)があります。\n");
setPluginResource( "dx11Shader", "kErrorVertexRequirement", "^1s^2s の頂点単位要件はサポートされていません。頂点サイズは ^3s ～ ^4s ですが、効果には ^5s が必要です\n");
setPluginResource( "dx11Shader", "kInvalidDx11ShaderNode", "無効な dx11Shader ノード: ^1s");
setPluginResource( "dx11Shader", "kLightBinding", "ライトのバインド");
setPluginResource( "dx11Shader", "kLightConnectionExplicitTip", "Maya シーンのライトとそのパラメータを fx ファイルで定義されたライトに明示的にバインドします。");
setPluginResource( "dx11Shader", "kLightConnectionImplicit", "自動バインド");
setPluginResource( "dx11Shader", "kLightConnectionImplicitNone", "なし");
setPluginResource( "dx11Shader", "kLightConnectionImplicitTip", "Maya は、シーンのライトとパラメータを fx ファイルで定義されたライトに自動的にバインドします。");
setPluginResource( "dx11Shader", "kLightConnectionNone", "シェーダ設定を使用");
setPluginResource( "dx11Shader", "kLightConnectionNoneTip", "Maya のライトを無視し、fx ファイル内の設定を使用します。");
setPluginResource( "dx11Shader", "kNiceNodeName", "DirectX 11 Shader");
setPluginResource( "dx11Shader", "kNoTextureType", "^1s にテクスチャ タイプが指定されていません。2D を仮定します\n");
setPluginResource( "dx11Shader", "kNoneDefined", "何も定義されていません");
setPluginResource( "dx11Shader", "kNotALight", "ライトではありません: ^1s");
setPluginResource( "dx11Shader", "kPrefDefaultEffectFile", "既定のエフェクト ファイル");
setPluginResource( "dx11Shader", "kPrefDx11ShaderPanel", "DX 11 Shader プリファレンス");
setPluginResource( "dx11Shader", "kPrefDx11ShaderTab", "    DX 11 Shader");
setPluginResource( "dx11Shader", "kPrefFileOpen", "開く");
setPluginResource( "dx11Shader", "kPrefSaveMsg", "プリファレンスを保存");
setPluginResource( "dx11Shader", "kPrefSavePrefsOrNotMsg", "dx11Shader プラグインは、プリファレンスをリフレッシュします。プリファレンス上の変更を保存しますか?");
setPluginResource( "dx11Shader", "kReloadAnnotation", "fx ファイルをリロード");
setPluginResource( "dx11Shader", "kReloadTool", "リロード");
setPluginResource( "dx11Shader", "kShader", "シェーダ");
setPluginResource( "dx11Shader", "kShaderFile", "シェーダ ファイル");
setPluginResource( "dx11Shader", "kShaderParameters", "パラメータ");
setPluginResource( "dx11Shader", "kSurfaceData", "サーフェス データ");
setPluginResource( "dx11Shader", "kTechnique", "テクニック");
setPluginResource( "dx11Shader", "kTechniqueTip", "fx ファイル内で定義されたレンダリング テクニックから選択します。");
setPluginResource( "dx11Shader", "kTypeBoolVector", "ブール ベクトル");
setPluginResource( "dx11Shader", "kTypeDouble", "ダブル");
setPluginResource( "dx11Shader", "kTypeIntUInt8", "uint8");
setPluginResource( "dx11Shader", "kTypeIntVector", "整数ベクトル");
setPluginResource( "dx11Shader", "kTypeStringVector", "文字列ベクトル");
setPluginResource( "dx11Shader", "kTypeTextureArray", "テクスチャ配列");
setPluginResource( "dx11Shader", "kUnknowSemantic", "パラメータ ^2s のセマンティック ^1s は認識できません\n");
setPluginResource( "dx11Shader", "kUnknowSpace", "パラメータ ^2s のスペース ^1s は認識できません\n");
setPluginResource( "dx11Shader", "kUnknownConnectableLight", "不明な接続可能ライト: ^1s");
setPluginResource( "dx11Shader", "kUnknownSceneObject", "不明なシーン オブジェクト: ^1s");
setPluginResource( "dx11Shader", "kUnknownTextureSemantic", "パラメータ ^2s のテクスチャ タイプ セマンティック ^1s は認識できません\n");
setPluginResource( "dx11Shader", "kUnknownUIGroup", "不明な UI グループ: ^1s");
setPluginResource( "dx11Shader", "kUnsupportedType", "パラメータ ^2s の ^1s はサポートされていません。パラメータは無視されます\n");
setPluginResource( "dx11Shader", "kWarningLog", "警告:\n^1s");
setPluginResource( "dx11Shader", "kWarningVertexRequirement", "^1s の頂点単位要件です。Maya で提供されているベクトル サイズは ^2s ですが、効果に必要なのは ^3s です\n");
// 
// --------------------------
// Registered node resources:
// --------------------------
// 
// Node: dx11Shader
// 
setNodeNiceNameResource( "dx11Shader", "DirectX 11 Shader" );
setAttrNiceNameResource( "dx11Shader", "s", "シェーダ" );
setAttrNiceNameResource( "dx11Shader", "ep", "エフェクト パラメータ" );
setAttrNiceNameResource( "dx11Shader", "t", "テクニック" );
setAttrNiceNameResource( "dx11Shader", "ts", "テクニック" );
setAttrNiceNameResource( "dx11Shader", "desc", "説明" );
setAttrNiceNameResource( "dx11Shader", "diag", "診断" );
setAttrNiceNameResource( "dx11Shader", "linfo", "ライト情報" );
// 
// Node: coneAngleToHotspotConverter
// 
setNodeNiceNameResource( "coneAngleToHotspotConverter", "ホットスポットに対する円錐角度のコンバータ" );
setAttrNiceNameResource( "coneAngleToHotspotConverter", "fzn", "フリーズ" );
setAttrNiceNameResource( "coneAngleToHotspotConverter", "ca", "円錐角度" );
setAttrNiceNameResource( "coneAngleToHotspotConverter", "pa", "周縁部の角度" );
setAttrNiceNameResource( "coneAngleToHotspotConverter", "hs", "ホットスポット" );
setAttrNiceNameResource( "coneAngleToHotspotConverter", "fo", "減衰" );
