// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//
//  Creation Date:	Feb 8, 1999
//
//  Procedure Name:
//	AEdynGlobalsTemplate
//
//  Description Name;
//	Creates the attribute editor controls for dynGlobals Node
//
//  Input Value:
//	nodeName 
//
//  Output Value:
//	None
// 

global proc useParticleDiskCacheCallback ( string $nodeName )
{
	string $nodeAttr = $nodeName + ".useParticleDiskCache";
	string $value = `getAttr $nodeAttr`;
	
	if ( $value ) {
		// enable attribute controls.
		// but keep the min and max frame locked
		//
		editorTemplate -dimControl $nodeName "cacheDirectory" false;
		editorTemplate -dimControl $nodeName "minFrameCached" false;
		editorTemplate -dimControl $nodeName "maxFrameCached" false;
	} else {
		editorTemplate -dimControl $nodeName "cacheDirectory" true;
		editorTemplate -dimControl $nodeName "minFrameCached" true;
		editorTemplate -dimControl $nodeName "maxFrameCached" true;
	}
}

global proc AEdynGlobalsTemplate ( string $nodeName )
{
	editorTemplate -beginScrollLayout;

		editorTemplate -beginLayout (uiRes("m_AEdynGlobalsTemplate.kOversampling"))  -collapse 0;

			editorTemplate -addControl "overSamples";

		editorTemplate -endLayout;

		editorTemplate -beginLayout (uiRes("m_AEdynGlobalsTemplate.kParticleDiskCache"))  -collapse 0;

			editorTemplate -addControl "useParticleDiskCache" "useParticleDiskCacheCallback";
			editorTemplate -addControl "cacheDirectory";
			editorTemplate -addControl "minFrameCached";
			editorTemplate -addControl "maxFrameCached";
			// setAttr -lock true ($nodeName + ".minFrameCached");
			// setAttr -lock true ($nodeName + ".maxFrameCached");

		editorTemplate -endLayout;

		// suppress some inherited attributes from the extras tab.
		//
		editorTemplate -suppress "nodeState";
		editorTemplate -suppress "caching";
		editorTemplate -suppress "pathVerified";
		editorTemplate -suppress "confirmSceneName";

		editorTemplate -addExtraControls;

	editorTemplate -endScrollLayout;
}

