// ===========================================================================
// Copyright 2022 Autodesk, Inc. All rights reserved.
//
// Use of this software is subject to the terms of the Autodesk license
// agreement provided at the time of installation or download, or which
// otherwise accompanies this software in either electronic or hard copy form.
// ===========================================================================
//
//
//  Creation Date:	2004
//

//  Procedure Name:  AEhairConstraintRelated
//
//  Description Name;
//		Return a list nodes related to the hairConstraint that we want to
//		display tabs for when the hairConstraint is in the AE.
//		For now the only related nodes will be pfxHair node.
//
//  Input Value:
//	   nodeName:  name of the hairConstraint node that is in the editor, that
//				  we are finding related nodes for.
//
//  Output Value:
//		The list of related nodes, with the node whose tab we want to be
//          opened, with the hairConstraint node added at the end of the
//          array.  
//
global proc string[] AEhairConstraintRelated (string $node)
{
	string $retval[];

	string $plugs[] = `listConnections -s false -d true -sh true $node`;

	// currently we show the related follicle and hairsystem nodes
	for( $plug in $plugs ) {
		if ( `nodeType $plug` == "hairSystem" ) {
			$retval[size($retval)] = $plug;
			break;
		}
	}
	$retval[size($retval)] = $node;
	$retval[size($retval)] = $node;

	return $retval;
}
